### ISSUE TITLE
no parsers found, using same .verb.md as the rest of the projects

### ISSUE THREAD

**Issue by osloarthur** [verbose/verb-generate-readme#21] opened 2017-09-08 09:16 UTC
We've got several projects with the same setup generating the readme, and now on a Windows 7 Enterprise system we get this error (using git bash):

    $ verb
    [11:12:28] starting verb
    [11:12:29] √ running tasks: [ 'verb-generate-readme' ]
    [11:12:29] starting verb.readme
    [11:12:29] starting verb.readme:default task
    [11:12:29] starting verb.readme:readme task
    Error: no parsers registered for: "

    >"
        at parse (C:\Users\art\AppData\Roaming\npm\node_modules\verb-generate-readme\node_modules\snapdragon\lib\parser.js:473:15)
        at Parser.parse (C:\Users\art\AppData\Roaming\npm\node_modules\verb-generate-readme\node_modules\snapdragon\lib\parser.js:477:24)
        at Snapdragon.parse (C:\Users\art\AppData\Roaming\npm\node_modules\verb-generate-readme\node_modules\snapdragon\index.js:122:28)
        at expand (C:\Users\art\AppData\Roaming\npm\node_modules\verb-generate-readme\node_modules\expand-reflinks\index.js:14:24)
        at C:\Users\art\AppData\Roaming\npm\node_modules\verb-generate-readme\node_modules\verb-reflinks\index.js:26:15
        at DestroyableTransform._transform (C:\Users\art\AppData\Roaming\npm\node_modules\verb-generate-readme\node_modules\gulp-reflinks\index.js:8:22)
        at DestroyableTransform.Transform._read (C:\Users\art\AppData\Roaming\npm\node_modules\verb-generate-readme\node_modules\readable-stream\lib\_stream_transform.js:182:10)
        at DestroyableTransform.Transform._write (C:\Users\art\AppData\Roaming\npm\node_modules\verb-generate-readme\node_modules\readable-stream\lib\_stream_transform.js:170:83)
        at doWrite (C:\Users\art\AppData\Roaming\npm\node_modules\verb-generate-readme\node_modules\readable-stream\lib\_stream_writable.js:406:64)
        at writeOrBuffer (C:\Users\art\AppData\Roaming\npm\node_modules\verb-generate-readme\node_modules\readable-stream\lib\_stream_writable.js:395:5)

Using latest versions of node(6 lts) npmjs verb and verb generate-readme

cc @phun-ky

**Comment by doowb** [comment] 2017-09-08 14:27
Hi @osloarthur, thanks for the issue.

It looks like that error is coming from `expand-reflinks` which uses `snapdragon` to parse reflinks from the markdown and find their real repository url to link to.

The syntax usually looks like `[some-repo][]`. It looks like with in `.verb.md` or in code comments there is something that might have some square brackets enclosing a string that starts with `"\n\n\n>"` (there might be some spaces in there too.

Are you able to provide the `.verb.md` and any code comments so we can try to track down what the cause is and figure out if we need to update `expand-reflinks`?

Also, one way to figure out if the issue is only in a specific file, you can remove helpers from `.verb.md` by escaping them with an additional `%`. So if you're using the `apidocs` helper like this `{%= apidocs('index.js') %}` you can escape it with `{%%= apidocs('index.js') %}`. This will at least help figure out if the reflink is in code comments or in the other docs.

**Comment by phun-ky** [comment] 2017-10-03 08:34
I figured it out. The `.verb.md` file was set to CRLF.. You can close this

**Closed** 2017-10-03 13:21 UTC
